---
title: "Land Cover Classification of Santa Barbara"
author:
  name: Eva Newby
date: December 7, 2024
format: html
execute: 
  warning: false
  error: false
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(sf)
library(terra)
library(here)
library(tidyverse)
library(rpart)
library(rpart.plot)
library(tmap)
```

## Load in landsat data
```{r}
filelist <- list.files(here("data", "landsat-data"), full.names = TRUE)

landsat <- rast(filelist)

names(landsat) <- c("blue", "green", "red", "NIR", "SWIR1", "SWIR2")
```

```{r}
plotRGB(landsat, r = 3, g = 2, b = 1, stretch = "lin")
```


## Load our Study area
```{r}
# Read in shapefile for portion of sb county
sb_county_south <- st_read(here("data", "SB_county_south.shp")) %>% 
  st_transform(., crs = crs(landsat))
```

```{r}
tm_shape(sb_county_south) +
  tm_borders()
```

```{r}
# Crop the landsat scene to the extent of the study area
landsat_cropped <- terra::crop(landsat, sb_county_south)

# mask the raster to the study area
landsat_masked <- terra::mask(landsat_cropped, sb_county_south)
```

```{r}
# Remove some objects
rm(landsat, sb_county_south, landsat_cropped)
```

```{r}
# plot rgb
plotRGB(landsat_masked, r=3, g=2, b=1, stretch = 'bin')
```

## Converting landsat values into reflectance

```{r}
# reclassify erroneous values as NA
rcl <- matrix(c(-Inf, 7273, NA,
                43636, Inf, NA),
              ncol = 3, byrow = TRUE)
```

```{r}
landsat <- terra::classify(landsat_masked, rcl = rcl)

# Adjust values based on scaling and additive factor
landsat <- (landsat* 0.0000275 - 0.2) * 100
summary(landsat)

```

## Training classifier
```{r}
training_data <- st_read(here::here("data", "trainingdata.shp")) %>%
  st_transform(., crs = crs(landsat))
```

```{r}
# Extract reflectance values at training sites
training_data_values <- terra::extract(landsat, training_data, df = TRUE)
```

```{r}
training_data_attributes <- training_data %>% 
  st_drop_geometry() 

sb_training_data <- left_join(training_data_values, training_data_attributes, by = c("ID" = "id")) %>% 
  mutate(type = as.factor(type))
```

```{r}
# Establish model formula
sb_formula <- type ~ red + green + blue + NIR + SWIR1 + SWIR2

# train decision tree
sb_decision_tree <- rpart(formula = sb_formula,
                          data = sb_training_data,
                          method = "class",
                          na.action = na.omit)
```

```{r}
prp(sb_decision_tree)
```

## Classify Image
```{r}
# Classify image based on decision tree
sb_classification <- terra::predict(landsat, sb_decision_tree,
                                    type = "class",
                                    na.rm = TRUE)

levels(sb_training_data$type)
levels(sb_classification)
```


# Time to map
```{r}
tm_shape(sb_classification) +
  tm_raster(palette = c("#8DB580", "#F2DDA4", "#7E8987", "#6A8EAE"),
labels = c("green vegetation", "soil/dead grass", "urban", "water"),
title = "Landcover type") +
  tm_layout(legend.position = c("left", "bottom"),
            main.title = "Santa Barbara Landcover")
```

